import Head from 'next/head'
import { Footer } from 'src/components/Footer'
import { Main } from 'src/components/Main'
import { Header } from 'src/components/Header'
import { useCounter } from "src/hooks/useCounter"
import { useBgLightBlue } from "src/hooks/useBgLightBlue"
import { useInputArray } from "src/hooks/useInputArray"

export default function Home() {
  const { count, isShow, handleClick, handleDisplay } = useCounter();
  const { text, array, handleChange, handleAdd } = useInputArray();
  useBgLightBlue();

  return (
    <>
      <Head>
        <title>Hello Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />

      {isShow ? <h1>{count}</h1> : null} 
      {/* JSX内if構文が使えないため、三項演算子で条件分岐する */}
      <button onClick={handleClick}>ボタン</button>
      <button onClick={handleDisplay}>{isShow ? "非表示" : "表示"}</button>

      <input type="text" value={text} onChange={handleChange} />
      <button onClick={handleAdd}>追加</button>
      <ul>
        {array.map(item => {
          return (
            <li key={item}>
              {item}
            </li>
          )
        })}
      </ul>

      <Main page="index"/>
      <Footer />
    </>
  )
}
