import Head from 'next/head'
import { Footer } from 'src/components/Footer'
import { Main } from 'src/components/Main'
import { Header } from 'src/components/Header'
import { useCallback, useEffect } from 'react'



export default function Home() {
  const foo = 1;

  const handleClick = useCallback((e) => {
    console.log(e.target.href);
    e.preventDefault();
    alert(foo)
  }, []);

  useEffect(() => {
    console.log("マウント時");
    document.body.style.backgroundColor="lightblue"; //mount時
    return () => {
      console.log("アンマウント時");
      document.body.style.backgroundColor=""; //unmount時
    };
  }, []);


  return (
    <>
      <Head>
        <title>Hello Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <a 
      href="/about" onClick={handleClick}>
        ボタン
      </a>
      <Main page="index"/>
      <Footer />
    </>
  )
}
